# Generated by Django 5.0 on 2023-12-15 16:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='products'), blank=True, null=True, size=None)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_letter_sizing', models.BooleanField(default=True)),
                ('sizes_letter', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, null=True)),
                ('sizes_number', models.DecimalField(blank=True, decimal_places=1, help_text='Numeric sizes: 1.0, 1.5, 2.0, etc.', max_digits=3, null=True)),
            ],
        ),
    ]
